/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ScheduleTemplateCreate,
  ScheduleTemplateResponse,
  ScheduleTemplateUpdate
} from '../../models';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listScheduleTemplatesResponse200 = {
  data: ScheduleTemplateResponse[]
  status: 200
}

export type listScheduleTemplatesResponseSuccess = (listScheduleTemplatesResponse200) & {
  headers: Headers;
};
;

export type listScheduleTemplatesResponse = (listScheduleTemplatesResponseSuccess)

export const getListScheduleTemplatesUrl = () => {




  return `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/`
}

/**
 * @summary List Schedule Templates
 */
export const listScheduleTemplates = async ( options?: RequestInit): Promise<listScheduleTemplatesResponse> => {

  const res = await fetch(getListScheduleTemplatesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listScheduleTemplatesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listScheduleTemplatesResponse
}





export const getListScheduleTemplatesQueryKey = () => {
    return [
    `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/`
    ] as const;
    }


export const getListScheduleTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof listScheduleTemplates>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScheduleTemplates>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListScheduleTemplatesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listScheduleTemplates>>> = ({ signal }) => listScheduleTemplates({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listScheduleTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListScheduleTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof listScheduleTemplates>>>
export type ListScheduleTemplatesQueryError = unknown


export function useListScheduleTemplates<TData = Awaited<ReturnType<typeof listScheduleTemplates>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScheduleTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listScheduleTemplates>>,
          TError,
          Awaited<ReturnType<typeof listScheduleTemplates>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListScheduleTemplates<TData = Awaited<ReturnType<typeof listScheduleTemplates>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScheduleTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listScheduleTemplates>>,
          TError,
          Awaited<ReturnType<typeof listScheduleTemplates>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListScheduleTemplates<TData = Awaited<ReturnType<typeof listScheduleTemplates>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScheduleTemplates>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Schedule Templates
 */

export function useListScheduleTemplates<TData = Awaited<ReturnType<typeof listScheduleTemplates>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listScheduleTemplates>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListScheduleTemplatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createScheduleTemplateResponse201 = {
  data: ScheduleTemplateResponse
  status: 201
}

export type createScheduleTemplateResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createScheduleTemplateResponseSuccess = (createScheduleTemplateResponse201) & {
  headers: Headers;
};
export type createScheduleTemplateResponseError = (createScheduleTemplateResponse422) & {
  headers: Headers;
};

export type createScheduleTemplateResponse = (createScheduleTemplateResponseSuccess | createScheduleTemplateResponseError)

export const getCreateScheduleTemplateUrl = () => {




  return `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/`
}

/**
 * @summary Create Schedule Template
 */
export const createScheduleTemplate = async (scheduleTemplateCreate: ScheduleTemplateCreate, options?: RequestInit): Promise<createScheduleTemplateResponse> => {

  const res = await fetch(getCreateScheduleTemplateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(scheduleTemplateCreate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createScheduleTemplateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createScheduleTemplateResponse
}





export const getCreateScheduleTemplateMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createScheduleTemplate>>, TError,{data: ScheduleTemplateCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createScheduleTemplate>>, TError,{data: ScheduleTemplateCreate}, TContext> => {

const mutationKey = ['createScheduleTemplate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createScheduleTemplate>>, {data: ScheduleTemplateCreate}> = (props) => {
          const {data} = props ?? {};

          return  createScheduleTemplate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateScheduleTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createScheduleTemplate>>>
    export type CreateScheduleTemplateMutationBody = ScheduleTemplateCreate
    export type CreateScheduleTemplateMutationError = HTTPValidationError

    /**
 * @summary Create Schedule Template
 */
export const useCreateScheduleTemplate = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createScheduleTemplate>>, TError,{data: ScheduleTemplateCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createScheduleTemplate>>,
        TError,
        {data: ScheduleTemplateCreate},
        TContext
      > => {
      return useMutation(getCreateScheduleTemplateMutationOptions(options), queryClient);
    }
    export type getScheduleTemplateResponse200 = {
  data: ScheduleTemplateResponse
  status: 200
}

export type getScheduleTemplateResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getScheduleTemplateResponseSuccess = (getScheduleTemplateResponse200) & {
  headers: Headers;
};
export type getScheduleTemplateResponseError = (getScheduleTemplateResponse422) & {
  headers: Headers;
};

export type getScheduleTemplateResponse = (getScheduleTemplateResponseSuccess | getScheduleTemplateResponseError)

export const getGetScheduleTemplateUrl = (scheduleTemplateId: string,) => {




  return `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/${scheduleTemplateId}`
}

/**
 * @summary Get Schedule Template
 */
export const getScheduleTemplate = async (scheduleTemplateId: string, options?: RequestInit): Promise<getScheduleTemplateResponse> => {

  const res = await fetch(getGetScheduleTemplateUrl(scheduleTemplateId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getScheduleTemplateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getScheduleTemplateResponse
}





export const getGetScheduleTemplateQueryKey = (scheduleTemplateId: string,) => {
    return [
    `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/${scheduleTemplateId}`
    ] as const;
    }


export const getGetScheduleTemplateQueryOptions = <TData = Awaited<ReturnType<typeof getScheduleTemplate>>, TError = HTTPValidationError>(scheduleTemplateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleTemplate>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetScheduleTemplateQueryKey(scheduleTemplateId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getScheduleTemplate>>> = ({ signal }) => getScheduleTemplate(scheduleTemplateId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: scheduleTemplateId !== null && scheduleTemplateId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getScheduleTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetScheduleTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof getScheduleTemplate>>>
export type GetScheduleTemplateQueryError = HTTPValidationError


export function useGetScheduleTemplate<TData = Awaited<ReturnType<typeof getScheduleTemplate>>, TError = HTTPValidationError>(
 scheduleTemplateId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleTemplate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduleTemplate>>,
          TError,
          Awaited<ReturnType<typeof getScheduleTemplate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScheduleTemplate<TData = Awaited<ReturnType<typeof getScheduleTemplate>>, TError = HTTPValidationError>(
 scheduleTemplateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleTemplate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getScheduleTemplate>>,
          TError,
          Awaited<ReturnType<typeof getScheduleTemplate>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetScheduleTemplate<TData = Awaited<ReturnType<typeof getScheduleTemplate>>, TError = HTTPValidationError>(
 scheduleTemplateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Schedule Template
 */

export function useGetScheduleTemplate<TData = Awaited<ReturnType<typeof getScheduleTemplate>>, TError = HTTPValidationError>(
 scheduleTemplateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getScheduleTemplate>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetScheduleTemplateQueryOptions(scheduleTemplateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateScheduleTemplateResponse200 = {
  data: ScheduleTemplateResponse
  status: 200
}

export type updateScheduleTemplateResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateScheduleTemplateResponseSuccess = (updateScheduleTemplateResponse200) & {
  headers: Headers;
};
export type updateScheduleTemplateResponseError = (updateScheduleTemplateResponse422) & {
  headers: Headers;
};

export type updateScheduleTemplateResponse = (updateScheduleTemplateResponseSuccess | updateScheduleTemplateResponseError)

export const getUpdateScheduleTemplateUrl = (scheduleTemplateId: string,) => {




  return `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/${scheduleTemplateId}`
}

/**
 * @summary Update Schedule Template
 */
export const updateScheduleTemplate = async (scheduleTemplateId: string,
    scheduleTemplateUpdate: ScheduleTemplateUpdate, options?: RequestInit): Promise<updateScheduleTemplateResponse> => {

  const res = await fetch(getUpdateScheduleTemplateUrl(scheduleTemplateId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(scheduleTemplateUpdate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateScheduleTemplateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateScheduleTemplateResponse
}





export const getUpdateScheduleTemplateMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateScheduleTemplate>>, TError,{scheduleTemplateId: string;data: ScheduleTemplateUpdate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateScheduleTemplate>>, TError,{scheduleTemplateId: string;data: ScheduleTemplateUpdate}, TContext> => {

const mutationKey = ['updateScheduleTemplate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateScheduleTemplate>>, {scheduleTemplateId: string;data: ScheduleTemplateUpdate}> = (props) => {
          const {scheduleTemplateId,data} = props ?? {};

          return  updateScheduleTemplate(scheduleTemplateId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateScheduleTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateScheduleTemplate>>>
    export type UpdateScheduleTemplateMutationBody = ScheduleTemplateUpdate
    export type UpdateScheduleTemplateMutationError = HTTPValidationError

    /**
 * @summary Update Schedule Template
 */
export const useUpdateScheduleTemplate = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateScheduleTemplate>>, TError,{scheduleTemplateId: string;data: ScheduleTemplateUpdate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateScheduleTemplate>>,
        TError,
        {scheduleTemplateId: string;data: ScheduleTemplateUpdate},
        TContext
      > => {
      return useMutation(getUpdateScheduleTemplateMutationOptions(options), queryClient);
    }
    export type deleteScheduleTemplateResponse204 = {
  data: void
  status: 204
}

export type deleteScheduleTemplateResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteScheduleTemplateResponseSuccess = (deleteScheduleTemplateResponse204) & {
  headers: Headers;
};
export type deleteScheduleTemplateResponseError = (deleteScheduleTemplateResponse422) & {
  headers: Headers;
};

export type deleteScheduleTemplateResponse = (deleteScheduleTemplateResponseSuccess | deleteScheduleTemplateResponseError)

export const getDeleteScheduleTemplateUrl = (scheduleTemplateId: string,) => {




  return `${process.env.NEXT_PUBLIC_V1_API_BASE_URL}/templates/schedule/${scheduleTemplateId}`
}

/**
 * @summary Delete Schedule Template
 */
export const deleteScheduleTemplate = async (scheduleTemplateId: string, options?: RequestInit): Promise<deleteScheduleTemplateResponse> => {

  const res = await fetch(getDeleteScheduleTemplateUrl(scheduleTemplateId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteScheduleTemplateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteScheduleTemplateResponse
}





export const getDeleteScheduleTemplateMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteScheduleTemplate>>, TError,{scheduleTemplateId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteScheduleTemplate>>, TError,{scheduleTemplateId: string}, TContext> => {

const mutationKey = ['deleteScheduleTemplate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteScheduleTemplate>>, {scheduleTemplateId: string}> = (props) => {
          const {scheduleTemplateId} = props ?? {};

          return  deleteScheduleTemplate(scheduleTemplateId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteScheduleTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteScheduleTemplate>>>

    export type DeleteScheduleTemplateMutationError = HTTPValidationError

    /**
 * @summary Delete Schedule Template
 */
export const useDeleteScheduleTemplate = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteScheduleTemplate>>, TError,{scheduleTemplateId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteScheduleTemplate>>,
        TError,
        {scheduleTemplateId: string},
        TContext
      > => {
      return useMutation(getDeleteScheduleTemplateMutationOptions(options), queryClient);
    }
