/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  WorkerResponse
} from '../../models';


export const getListWorkersResponseMock = (): WorkerResponse[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getCreateWorkerResponseMock = (overrideResponse: Partial<Extract<WorkerResponse, object>> = {}): WorkerResponse => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetWorkerResponseMock = (overrideResponse: Partial<Extract<WorkerResponse, object>> = {}): WorkerResponse => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateWorkerResponseMock = (overrideResponse: Partial<Extract<WorkerResponse, object>> = {}): WorkerResponse => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getListWorkersMockHandler = (overrideResponse?: WorkerResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<WorkerResponse[]> | WorkerResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/workers/', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListWorkersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateWorkerMockHandler = (overrideResponse?: WorkerResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<WorkerResponse> | WorkerResponse), options?: RequestHandlerOptions) => {
  return http.post('*/workers/', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateWorkerResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetWorkerMockHandler = (overrideResponse?: WorkerResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<WorkerResponse> | WorkerResponse), options?: RequestHandlerOptions) => {
  return http.get('*/workers/:workerId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetWorkerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateWorkerMockHandler = (overrideResponse?: WorkerResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<WorkerResponse> | WorkerResponse), options?: RequestHandlerOptions) => {
  return http.put('*/workers/:workerId', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateWorkerResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteWorkerMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/workers/:workerId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getWorkersMock = () => [
  getListWorkersMockHandler(),
  getCreateWorkerMockHandler(),
  getGetWorkerMockHandler(),
  getUpdateWorkerMockHandler(),
  getDeleteWorkerMockHandler()
]
