version: '3'
services:
  web:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/home/node/app
      # - api-go-cache:/go/pkg
    ports:
      - '4000:4000'
    expose: 
      - '4000'
    environment:
      - ADDR=0.0.0.0:3000
      - PORT=4000
      - FAST_REFRESH=true
    depends_on:
      - api
    networks:
      - apinet
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/go/src
      - api-go-cache:/go/pkg
      - ./openapi:/openapi
    ports:
      - '3000:3000'
    expose: 
      - '3000'
    environment:
      - ADDR=0.0.0.0
      - DATABASE_URL=postgres://scheduler:scheduler@db:5432/scheduler?sslmode=disable&connect_timeout=10
      - TEST_DATABASE_URL=postgres://scheduler:scheduler@db:5432/scheduler_test?sslmode=disable&connect_timeout=10
    depends_on:
      - db
    networks:
      - dbnet
      - apinet
    restart: unless-stopped

  db:
    image: postgres:15.4@sha256:d1168ad5397bf9c94cc417c530469805a8767ed585481d93f174461ac8557e3a
    networks:
      - dbnet
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
      POSTGRES_DB: scheduler
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d scheduler -u scheduler" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:
  api-go-cache:

networks:
  dbnet:
  apinet: