[project]
name = "scheduler-api"
version = "0.1.0"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
  ".",
  "./api"
]
testpaths = [
  "api/scheduler_api/tests"
]
