package actions

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"github.com/blbecker/scheduler/api/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Worker)
// DB Table: Plural (workers)
// Resource: Plural (Workers)
// Path: Plural (/workers)
// View Template Folder: Plural (/templates/workers/)

// WorkersResource is the resource for the Worker model
type WorkersResource struct {
	buffalo.Resource
}

// List gets all Workers. This function is mapped to the path
// GET /workers
func (v WorkersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	workers := &models.Workers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Workers from the DB
	if err := q.All(workers); err != nil {
		return err
	}

	log.Default().Printf("Returning %v workers", len(*workers))

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("workers", workers)
		return c.Render(http.StatusOK, r.HTML("workers/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(workers))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(workers))
	}).Respond(c)
}

// Show gets the data for one Worker. This function is mapped to
// the path GET /workers/{worker_id}
func (v WorkersResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Worker
	worker := &models.Worker{}

	// To find the Worker the parameter worker_id is used.
	if err := tx.Find(worker, c.Param("worker_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("worker", worker)

		return c.Render(http.StatusOK, r.HTML("workers/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(worker))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(worker))
	}).Respond(c)
}

// Create adds a Worker to the DB. This function is mapped to the
// path POST /workers
func (v WorkersResource) Create(c buffalo.Context) error {
	// Allocate an empty Worker
	worker := &models.Worker{}

	// Bind worker to the html form elements
	if err := c.Bind(worker); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(worker)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("worker", worker)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("workers/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "worker.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/workers/%v", worker.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(worker))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(worker))
	}).Respond(c)
}

// Update changes a Worker in the DB. This function is mapped to
// the path PUT /workers/{worker_id}
func (v WorkersResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Worker
	worker := &models.Worker{}

	if err := tx.Find(worker, c.Param("worker_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Worker to the html form elements
	if err := c.Bind(worker); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(worker)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("worker", worker)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("workers/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "worker.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/workers/%v", worker.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(worker))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(worker))
	}).Respond(c)
}

// Destroy deletes a Worker from the DB. This function is mapped
// to the path DELETE /workers/{worker_id}
func (v WorkersResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Worker
	worker := &models.Worker{}

	// To find the Worker the parameter worker_id is used.
	if err := tx.Find(worker, c.Param("worker_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(worker); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "worker.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/workers")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(worker))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(worker))
	}).Respond(c)
}
