/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import type { SchedulerApiSchemasSolveScheduleSolveStatusResult } from './schedulerApiSchemasSolveScheduleSolveStatusResult';
import type { ScheduleSolveParameters } from './scheduleSolveParameters';

/**
 * Response for schedule solve status.
 */
export interface SchedulerApiSchemasSolveScheduleSolveStatus {
  id: string;
  /** pending, running, completed, failed */
  status: string;
  template_id: string;
  parameters: ScheduleSolveParameters;
  created_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  current_generation?: number | null;
  best_fitness?: number | null;
  /** Progress 0-1 */
  progress?: number | null;
  result?: SchedulerApiSchemasSolveScheduleSolveStatusResult;
  error_message?: string | null;
}
