/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */

export interface ScheduleResponse {
  id: string;
  schedule_template_id: string;
  name: string;
  created_at: string;
  updated_at: string;
}
