/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Additional solve metrics
 */
export type ScheduleSolveResultMetrics = { [key: string]: unknown };
