/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleSolveParameters } from './scheduleSolveParameters';

/**
 * Request to create a schedule solve.
 */
export interface ScheduleSolveRequest {
  /** ID of the schedule template to solve for */
  template_id: string;
  parameters: ScheduleSolveParameters;
}
