/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleSolveParameters } from './scheduleSolveParameters';

/**
 * Response for schedule solve creation.
 */
export interface ScheduleSolveCreateResponse {
  id: string;
  /** pending, queued, running, completed, failed */
  status?: string;
  template_id: string;
  parameters: ScheduleSolveParameters;
  /** ID of the persisted ScheduleSolveModel record */
  schedule_solve_id: string;
}
