/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduleSolveResultBestGenome } from './scheduleSolveResultBestGenome';
import type { ScheduleSolveResultMetrics } from './scheduleSolveResultMetrics';

/**
 * Response for schedule solve result.
 */
export interface ScheduleSolveResult {
  id: string;
  /** completed, failed */
  status: string;
  best_genome?: ScheduleSolveResultBestGenome;
  /** Fitness score of best genome (0.0-1.0) */
  best_fitness: number;
  /** Number of generations executed */
  generations: number;
  /** Time taken in seconds */
  elapsed_time: number;
  /** Additional solve metrics */
  metrics?: ScheduleSolveResultMetrics;
  created_at: string;
}
