/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */

export interface ShiftUpdate {
  schedule_id?: string | null;
  shift_template_id?: string | null;
  name?: string | null;
  start_time?: string | null;
  end_time?: string | null;
}
