/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */

export interface SkillResponse {
  id: string;
  name: string;
  description: string | null;
  created_at: string;
  updated_at: string;
}
