openapi: '3.0.3'
info:
  title: Scheduler Application
  version: '1.0.0'
servers:
  - url: https://api.server.test/v1
paths:
  /user:
    get:
      responses:
        '404':
          description: OK
