import StyledComponentsRegistry from '@/lib/AntdRegistry'
import { Layout } from 'antd'
import { Content } from 'antd/es/layout/layout'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Layout>
        <Content         >
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </Content>
      </Layout>
      </body>

    </html>
  )
}
