"""organize models

Revision ID: 07a8acd75419
Revises: 384f515d3d78
Create Date: 2026-07-03 05:33:43.290623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07a8acd75419'
down_revision: Union[str, Sequence[str], None] = '384f515d3d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_templates_id'), 'schedule_templates', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_template_id'], ['schedule_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_schedule_template_id'), 'schedules', ['schedule_template_id'], unique=False)
    op.create_table('shift_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_template_id'], ['schedule_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_templates_id'), 'shift_templates', ['id'], unique=False)
    op.create_index(op.f('ix_shift_templates_schedule_template_id'), 'shift_templates', ['schedule_template_id'], unique=False)
    op.create_table('worker_skill_links',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'skill_id')
    )
    op.create_table('schedule_generation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_template_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_template_id'], ['schedule_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_generation_runs_id'), 'schedule_generation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_generation_runs_schedule_id'), 'schedule_generation_runs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_generation_runs_schedule_template_id'), 'schedule_generation_runs', ['schedule_template_id'], unique=False)
    op.create_index(op.f('ix_schedule_generation_runs_status'), 'schedule_generation_runs', ['status'], unique=False)
    op.create_table('shift_template_skills',
    sa.Column('shift_template_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_template_id', 'skill_id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('shift_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_schedule_id'), 'shifts', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_shifts_shift_template_id'), 'shifts', ['shift_template_id'], unique=False)
    op.create_table('shift_skill_links',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_id', 'skill_id')
    )
    op.create_table('shift_worker_links',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_id', 'worker_id')
    )
    op.drop_table('shiftworkerlink')
    op.drop_table('shift')
    op.drop_table('workerskilllink')
    op.drop_table('worker')
    op.drop_table('shiftskilllink')
    op.drop_table('skill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shiftskilllink',
    sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('shiftskilllink_shift_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('shiftskilllink_skill_id_fkey')),
    sa.PrimaryKeyConstraint('shift_id', 'skill_id', name=op.f('shiftskilllink_pkey'))
    )
    op.create_table('worker',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='worker_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workerskilllink',
    sa.Column('worker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('workerskilllink_skill_id_fkey')),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name=op.f('workerskilllink_worker_id_fkey')),
    sa.PrimaryKeyConstraint('worker_id', 'skill_id', name=op.f('workerskilllink_pkey'))
    )
    op.create_table('shift',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shift_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('shiftworkerlink',
    sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], name=op.f('shiftworkerlink_shift_id_fkey')),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], name=op.f('shiftworkerlink_worker_id_fkey')),
    sa.PrimaryKeyConstraint('shift_id', 'worker_id', name=op.f('shiftworkerlink_pkey'))
    )
    op.drop_table('shift_worker_links')
    op.drop_table('shift_skill_links')
    op.drop_index(op.f('ix_shifts_shift_template_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_schedule_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_table('shift_template_skills')
    op.drop_index(op.f('ix_schedule_generation_runs_status'), table_name='schedule_generation_runs')
    op.drop_index(op.f('ix_schedule_generation_runs_schedule_template_id'), table_name='schedule_generation_runs')
    op.drop_index(op.f('ix_schedule_generation_runs_schedule_id'), table_name='schedule_generation_runs')
    op.drop_index(op.f('ix_schedule_generation_runs_id'), table_name='schedule_generation_runs')
    op.drop_table('schedule_generation_runs')
    op.drop_table('worker_skill_links')
    op.drop_index(op.f('ix_shift_templates_schedule_template_id'), table_name='shift_templates')
    op.drop_index(op.f('ix_shift_templates_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    op.drop_index(op.f('ix_schedules_schedule_template_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_schedule_templates_id'), table_name='schedule_templates')
    op.drop_table('schedule_templates')
    # ### end Alembic commands ###
