"""add_shift_assignments_and_update_models

Revision ID: 08234859460f
Revises: 9ac1b144ecb2
Create Date: 2026-07-11 03:50:53.273653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "08234859460f"
down_revision: Union[str, Sequence[str], None] = "9ac1b144ecb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shift_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=False),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("ASSIGNED", name="shiftassignmentstatus"), nullable=False
        ),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shift_id"], ["shifts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["worker_id"], ["workers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shift_assignments_id"), "shift_assignments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_shift_assignments_schedule_id"),
        "shift_assignments",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shift_assignments_shift_id"),
        "shift_assignments",
        ["shift_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_shift_assignments_worker_id"),
        "shift_assignments",
        ["worker_id"],
        unique=False,
    )
    op.drop_table("shift_worker_links")
    op.drop_index(op.f("ix_shifts_schedule_id"), table_name="shifts")
    op.drop_constraint(op.f("shifts_schedule_id_fkey"), "shifts", type_="foreignkey")
    op.drop_column("shifts", "schedule_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shifts",
        sa.Column("schedule_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("shifts_schedule_id_fkey"),
        "shifts",
        "schedules",
        ["schedule_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_shifts_schedule_id"), "shifts", ["schedule_id"], unique=False
    )
    op.create_table(
        "shift_worker_links",
        sa.Column("shift_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("worker_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["shifts.id"],
            name=op.f("shift_worker_links_shift_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
            name=op.f("shift_worker_links_worker_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "shift_id", "worker_id", name=op.f("shift_worker_links_pkey")
        ),
    )
    op.drop_index(
        op.f("ix_shift_assignments_worker_id"), table_name="shift_assignments"
    )
    op.drop_index(op.f("ix_shift_assignments_shift_id"), table_name="shift_assignments")
    op.drop_index(
        op.f("ix_shift_assignments_schedule_id"), table_name="shift_assignments"
    )
    op.drop_index(op.f("ix_shift_assignments_id"), table_name="shift_assignments")
    op.drop_table("shift_assignments")
    # ### end Alembic commands ###
