"""make shift assignment worker_id nullable

Revision ID: 4ce62f371610
Revises: 08234859460f
Create Date: 2026-07-11 04:49:22.021623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4ce62f371610"
down_revision: Union[str, Sequence[str], None] = "08234859460f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shift_assignments", "worker_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shift_assignments", "worker_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
