"""schedule solves

Revision ID: 7076bbb1c7cf
Revises: 07a8acd75419
Create Date: 2026-07-10 19:43:34.300684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7076bbb1c7cf"
down_revision: Union[str, Sequence[str], None] = "07a8acd75419"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_solves",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("schedule_template_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("celery_task_id", sa.String(), nullable=True),
        sa.Column("current_generation", sa.Integer(), nullable=True),
        sa.Column("best_fitness", sa.Float(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error_details", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["schedule_template_id"], ["schedule_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedule_solves_celery_task_id"),
        "schedule_solves",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_solves_id"), "schedule_solves", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_solves_schedule_id"),
        "schedule_solves",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_solves_schedule_template_id"),
        "schedule_solves",
        ["schedule_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_solves_status"), "schedule_solves", ["status"], unique=False
    )
    op.drop_index(
        op.f("ix_schedule_generation_runs_id"), table_name="schedule_generation_runs"
    )
    op.drop_index(
        op.f("ix_schedule_generation_runs_schedule_id"),
        table_name="schedule_generation_runs",
    )
    op.drop_index(
        op.f("ix_schedule_generation_runs_schedule_template_id"),
        table_name="schedule_generation_runs",
    )
    op.drop_index(
        op.f("ix_schedule_generation_runs_status"),
        table_name="schedule_generation_runs",
    )
    op.drop_table("schedule_generation_runs")
    op.add_column("schedules", sa.Column("schedule_solve_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_schedules_schedule_solve_id"),
        "schedules",
        ["schedule_solve_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "schedules",
        "schedule_solves",
        ["schedule_solve_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedules", type_="foreignkey")
    op.drop_index(op.f("ix_schedules_schedule_solve_id"), table_name="schedules")
    op.drop_column("schedules", "schedule_solve_id")
    op.create_table(
        "schedule_generation_runs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "schedule_template_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("schedule_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("schedule_generation_runs_schedule_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_template_id"],
            ["schedule_templates.id"],
            name=op.f("schedule_generation_runs_schedule_template_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("schedule_generation_runs_pkey")),
    )
    op.create_index(
        op.f("ix_schedule_generation_runs_status"),
        "schedule_generation_runs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_generation_runs_schedule_template_id"),
        "schedule_generation_runs",
        ["schedule_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_generation_runs_schedule_id"),
        "schedule_generation_runs",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_generation_runs_id"),
        "schedule_generation_runs",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_schedule_solves_status"), table_name="schedule_solves")
    op.drop_index(
        op.f("ix_schedule_solves_schedule_template_id"), table_name="schedule_solves"
    )
    op.drop_index(op.f("ix_schedule_solves_schedule_id"), table_name="schedule_solves")
    op.drop_index(op.f("ix_schedule_solves_id"), table_name="schedule_solves")
    op.drop_index(
        op.f("ix_schedule_solves_celery_task_id"), table_name="schedule_solves"
    )
    op.drop_table("schedule_solves")
    # ### end Alembic commands ###
