"""remove_schedule_solve_id_from_schedules

Revision ID: 9ac1b144ecb2
Revises: 7076bbb1c7cf
Create Date: 2026-07-10 21:12:58.123316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9ac1b144ecb2"
down_revision: Union[str, Sequence[str], None] = "7076bbb1c7cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedules_schedule_solve_id"), table_name="schedules")
    op.drop_constraint(
        op.f("schedules_schedule_solve_id_fkey"), "schedules", type_="foreignkey"
    )
    op.drop_column("schedules", "schedule_solve_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column("schedule_solve_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("schedules_schedule_solve_id_fkey"),
        "schedules",
        "schedule_solves",
        ["schedule_solve_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_schedules_schedule_solve_id"),
        "schedules",
        ["schedule_solve_id"],
        unique=False,
    )
    # ### end Alembic commands ###
