/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  ShiftTemplateResponse
} from '../../models';


export const getListShiftTemplatesResponseMock = (): ShiftTemplateResponse[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), schedule_template_id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), start_time: faker.string.alpha({length: {min: 10, max: 20}}), end_time: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})))

export const getCreateShiftTemplateResponseMock = (overrideResponse: Partial<Extract<ShiftTemplateResponse, object>> = {}): ShiftTemplateResponse => ({id: faker.string.uuid(), schedule_template_id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), start_time: faker.string.alpha({length: {min: 10, max: 20}}), end_time: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetShiftTemplateResponseMock = (overrideResponse: Partial<Extract<ShiftTemplateResponse, object>> = {}): ShiftTemplateResponse => ({id: faker.string.uuid(), schedule_template_id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), start_time: faker.string.alpha({length: {min: 10, max: 20}}), end_time: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateShiftTemplateResponseMock = (overrideResponse: Partial<Extract<ShiftTemplateResponse, object>> = {}): ShiftTemplateResponse => ({id: faker.string.uuid(), schedule_template_id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), start_time: faker.string.alpha({length: {min: 10, max: 20}}), end_time: faker.string.alpha({length: {min: 10, max: 20}}), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', updated_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

