/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type { ShiftResponse } from "../../models";

export const getListShiftsResponseMock = (): ShiftResponse[] =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.uuid(),
    schedule_id: faker.string.uuid(),
    shift_template_id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    start_time: faker.date.past().toISOString().slice(0, 19) + "Z",
    end_time: faker.date.past().toISOString().slice(0, 19) + "Z",
    created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  }));

export const getCreateShiftResponseMock = (
  overrideResponse: Partial<Extract<ShiftResponse, object>> = {},
): ShiftResponse => ({
  id: faker.string.uuid(),
  schedule_id: faker.string.uuid(),
  shift_template_id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  start_time: faker.date.past().toISOString().slice(0, 19) + "Z",
  end_time: faker.date.past().toISOString().slice(0, 19) + "Z",
  created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getGetShiftResponseMock = (
  overrideResponse: Partial<Extract<ShiftResponse, object>> = {},
): ShiftResponse => ({
  id: faker.string.uuid(),
  schedule_id: faker.string.uuid(),
  shift_template_id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  start_time: faker.date.past().toISOString().slice(0, 19) + "Z",
  end_time: faker.date.past().toISOString().slice(0, 19) + "Z",
  created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});

export const getUpdateShiftResponseMock = (
  overrideResponse: Partial<Extract<ShiftResponse, object>> = {},
): ShiftResponse => ({
  id: faker.string.uuid(),
  schedule_id: faker.string.uuid(),
  shift_template_id: faker.string.uuid(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  start_time: faker.date.past().toISOString().slice(0, 19) + "Z",
  end_time: faker.date.past().toISOString().slice(0, 19) + "Z",
  created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
  ...overrideResponse,
});
