/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Scheduler API
 * OpenAPI spec version: 0.1.0
 */

export interface Shift {
  id: string;
  start_time: string;
  endTime: string;
  location?: string;
  notes?: string;
}
