FROM golang:1.20-alpine3.17@sha256:ecccf4963ae76531a65b9029326c803212c20119dcf924f8157e59f6aa664b35

RUN go install -tags sqlite github.com/gobuffalo/cli/cmd/buffalo@v0.18.14 && \
    buffalo version

RUN apk add bind-tools git bash wget postgresql-client && \
    wget https://raw.githubusercontent.com/cippaciong/buffalo_bash_completion/master/buffalo_completion.sh -O $HOME/buffalo_completion.sh && \
    echo source /root/buffalo_completion.sh >> $HOME/.bashrc

RUN go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.0.0

WORKDIR /go/src

CMD buffalo dev
