name: "Scheduler (Build/Test)"
on:
  pull_request:

jobs:
    api_tests:
      runs-on: ubuntu-latest
      container:
        image: gobuffalo/buffalo:v0.18.14
        ports:
          - 80
        # volumes:
        #   - my_docker_volume:/volume_mount
        # options: --cpus 1
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1

        - name: Setup testing dependencies
          run: |
            cd api
            go get github.com/axw/gocov/gocov
            go get github.com/AlekSi/gocov-xml
            go mod download

        - name: Execute buffalo test (probably)
          run: |
            cd api
            buffalo test -coverprofile=coverage.out ./...
            gocov convert cover.out | gocov-xml > coverage.xml
        
        - name: Code Coverage Report
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: coverage.xml
            badge: true
            fail_below_min: true
            format: markdown
            hide_branch_rate: false
            hide_complexity: false
            indicators: true
            output: both
            thresholds: '60 80'